spring:
    application:
        name: wes-argo-api

server:
    port : 8080

elastic:
    host: localhost
    port: 9200
    useHttps: false
    useAuthentication: false
    username: elastic
    password: testing
    maestroIndex: file_centric_1.0

graphql:
    servlet:
        mapping: /graphql
        enabled: true
        corsEnabled: true
    playground:
        enabled: true
        cdn:
            enabled: false
