spring:
    application:
        name: wes-argo-api

server:
    port : 8080

elastic:
    host: localhost
    port: 9200
    workflowIndex: workflow
    taskIndex: task
    maestroIndex: file_centric_1.0

graphql:
    servlet:
        mapping: /graphql
        enabled: true
        corsEnabled: true
        # if you want to @ExceptionHandler annotation for custom GraphQLErrors
#        exception-handlers-enabled: true
#        contextSetting: PER_REQUEST_WITH_INSTRUMENTATION
